### ISSUE TITLE
Rendre l'appli servable dans un sous-dossier

### ISSUE THREAD

**Issue by boogheta** [AtelierCartographie/mapp#1]
À l'heure actuelle l'appli ne peut fonctionner que servie directement à la racine d'un domaine du fait de liens absolus vers les ressources css/js etc.
Il est important par exemple pour monter une préprod que l'on puisse servir l'appli dans un sous-dossier

**Comment by apezel** [comment]
Ok, en fait cette fonctionnalité est déjà en place pour les js et la css : il faut modifier la variable baseURL dans le fichier config/environment. Cela nécessite un rebuild. L'application utilisant les fragments d'URL HTML5 il est indispensable de renseigner le sous-dossier afin que le système puisse différencier les fragments de l'URL véritable.
Pour ce qui est du chargement de resources statiques autres comme les fonds de carte ou les données de test j'ai ajouté le support du sous dossier dans le dernier commit.

**Comment by apezel** [comment]
Pour info. il est possible de créer des configurations spécifiques dans le fichier config/environment (voir environment="development"). L'environment de destination pourra être renseigné lors du build ( ex : ember build --environment=preprod )

**Comment by boogheta** [comment]
This is a bit problematic that the configured url path needs to be set in a file committed in the sourcecode, is there a way to set some of the options via some command line options (something like `ember build --option baseURL=/carto/`) ?
Otherwise, the config files should only be examples files in the repo and replicated at Install so one can modify them without touching the source code of the app.

**Comment by boogheta** [comment]
(je ne sais pas trop pourquoi j'ai écrit ça en anglais...)

Pour illustration voici le script de génération de préprod avec la réécriture du fichier environment que je suis contraint de faire en l'état pour contourner le souci:
```bash
cd /var/opt/carto
git checkout -- config/environment.js
git pull
cat config/environment.js | sed "s|if (environment === 'production') {|if (environment === 'production') {\n    ENV.baseURL = '/carto/';|" > config/environment.js.new
mv -f config/environment.js.new config/environment.js
npm install
bower install
ember build --environment=production
```

**Comment by apezel** [comment]
Je n'ai peut-être pas été clair dans mon précédent message : il est possible de créer d'autres environment que ceux de production et de développement. Il suffit donc d'ajouter un environment avec la bonne baseURL dans le fichier environment.js et de compiler avec ember build --environment=mon_nouvel_environment.
Je peux l'ajouter moi même si cette modif te pose problème. Sinon il suffit que tu édites ce fichier et que tu pousses le code.

**Comment by boogheta** [comment]
J'ai bien compris, mais on n'inclut pas un chemin configurable propre possiblement à différentes versions dans un repository, cette configuration devrait etre un fichier exemple à copier lors de la première installation

**Comment by apezel** [comment]
Je n'ai pas vraiment la réponse à ce problème dans la mesure ou ember-cli ne propose pas cette fonctionnalité (à ma connaissance). Mais c'est le but du fichier environment.js : baseURL n'est pas la seule option disponible dans ce fichier et on peut supposer qu'une installe spécifique voudrait configurer certaines propriétés différemment (ou configurer plusieurs environment). Exemple : augmenter le niveau de log. Je pense donc qu'il est préférable de trouver une solution avec git de manière à ne pas mettre à jour ce fichier lors des push. On pourrait utiliser git update-index --assume-unchanged config/environment.js . Cette option présente l'avantage d'être totalement réversible mais doit se faire sur chaque poste. Sinon il faut créer un environment.js.tpl et ajouter environment.js au .gitignore. Qu'en penses-tu ?

**Comment by boogheta** [comment]
La dernière solution est à mon avis la bonne pratique, c'est ce que j'entendais dans mes précédents messages par un fichier exemple à copier lors de la première install

**Comment by apezel** [comment]
Ok parfait, je fais ça lundi.

**Comment by boogheta** [comment]
super, merci beaucoup
